:sparkles: [#483] add description for radio en checkbox option
open-formulieren/formio-builder pull request #131
Opened 2024-03-06 11:42 UTC by nikkiysendoorn1

2024-03-06 13:16 UTC, Viicos reviewed
If I remember correctly, the issue was to add a description for checkboxes in the SDK (that is, available to the end user). In the form builder (this repo), we actually need to add a text input for each option where the description, so probably a 3rd column here:

![image](https://github.com/open-formulieren/formio-builder/assets/65306057/8354ecf3-67eb-4d11-ad77-5e6290998b76)

? Maybe we should confirm with @joeribekker

2024-03-11 17:19 UTC, sergei-maertens reviewed
Couple thoughts/remarks:

* the description takes up too much space. Rather, make this "second row" collapsed by default, and add a link/icon to "edit option description" which expands/collapses it on click
* I can't seem to enter translations yet for these descriptions :)

2024-03-13 16:59 UTC, sergei-maertens requested changes
What I meant was that when I enter the description of an option, there's no way to go to the "translations" tab and enter the Dutch/English translation for that same description.

If a form is being filled out in English, the option labels (and descriptions) must display their english translations instead of the default/Dutch translations. Currently the person defining the form cannot enter these translations anywhere.

2024-03-13 16:59 UTC, sergei-maertens commented on src/components/builder/values/option-row.tsx
> +            })}
```suggestion
            aria-label={intl.formatMessage({
              description: 'Accessible label for option description',
              defaultMessage: 'Option description',
            })}
```

2024-03-20 13:56 UTC, sergei-maertens approved these changes
I've done some more UI tweaks :)

2024-03-20 14:08 UTC, merged