[open-formulieren/open-forms#4267] Take new IOT API endpoint into account
open-formulieren/formio-builder pull request #169
Opened 2024-07-17 09:08 UTC by Viicos

Partly fixes open-formulieren/open-forms#4267

2024-07-17 12:23 UTC, Viicos commented
This one is required by https://github.com/open-formulieren/open-forms/pull/4507

2024-07-18 09:39 UTC, sergei-maertens requested changes

2024-07-18 09:39 UTC, sergei-maertens commented on src/registry/file/registration-tab.stories.ts
> +      expect(canvas.getByText('Open Zaak > Test catalogus name', {exact: true})).toBeVisible();
I think this can/should be reverted now :)

2024-07-18 09:50 UTC, sergei-maertens approved these changes

2024-07-18 09:56 UTC, merged