Adding map interaction config
open-formulieren/formio-builder pull request #198
Opened 2024-12-11 14:10 UTC by robinmolen

Part of open-formulieren/open-forms#2177

This relies on a update to the types repo

2024-12-16 10:57 UTC, robinmolen commented
Because this feature will be added after 3.0, this PR is moved to draft.

This PR is still ready to be reviewed, it just shouldn't be merged just yet

2024-12-17 08:26 UTC, vaszig reviewed
As far as I can say, it seems good to me. I would add though some stories for the interactions (not necessarily tests, but just to have the appearance).

2024-12-18 13:09 UTC, robinmolen commented
> As far as I can say, it seems good to me. I would add though some stories for the interactions (not necessarily tests, but just to have the appearance).

The map component stories do show the configuration, but the choice doesn't have a visual representation.
But yeah, it would probably be nice to show/test the interaction options in the builder..

2025-01-06 10:48 UTC, robinmolen commented
This PR can be reviewed (this includes some chromatic changes that also have to be reviewed)

In the formio-builder a new map component configuration option was added: `interactions`. "Interactions" is a group of checkboxes, allowing different user interactions in the map. To keep the logic close to what we already have, the `pointer` interaction is activated by default.

In the form builder map component preview you can test/use the active interactions.

2025-01-08 11:38 UTC, sergei-maertens requested changes
Can we move *all* of the map settings to a separate tab? Tab title can be "Map settings" or just "Settings", and would come after the "Validation" tab. I think the "Basic" tab is getting too clutter.

Specifically, this means the fields:

* Use globally configured map component settings
* Map configuration (and re-label this to "Initial focus" or something like that)
* Tile layer
* Available interactions

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Lijn interacties",
```suggestion
    "defaultMessage": "Lijn",
```
I feel like "interactions" is repeated way too much. I'm also inclined to rephrase this as "available drawing shapes" to make it simpler?

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Geeft gebruikers de mogelijkheid een lijn te tekenen, wanneer ze met het kaartmateriaal werken",
```suggestion
    "defaultMessage": "Gebruikers kunnen rechte lijnen tekenen op de kaart.",
```

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Geeft gebruikers de mogelijkheid een lijn te tekenen, wanneer ze met het kaartmateriaal werken",
is it one or more lines, or just one? Probably good to clarify that in the tooltip.

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Polygoon interacties",
```suggestion
    "defaultMessage": "Veelhoek (polygoon)",
```

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Mogelijke kaartmateriaal interacties",
```suggestion
    "defaultMessage": "Mogelijke kaartmateriaalinteracties",
```
single samengesteld woord

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Geeft gebruikers de mogelijkheid een polygoon te tekenen, wanneer ze met het kaartmateriaal werken",
```suggestion
    "defaultMessage": "Gebruikers kunnen een veelhoek (gesloten vorm die uit rechte lijnen bestaat) tekenen.",
```

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Pin interacties",
```suggestion
    "defaultMessage": "Pin/punt",
```

2025-01-08 11:38 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Geeft gebruikers de mogelijkheid een pin te plaatsen, wanneer ze met het kaartmateriaal werken",
```suggestion
    "defaultMessage": "Gebruikers kunnen een punt aanduiden op de kaart.",
```

2025-01-08 11:38 UTC, sergei-maertens commented on src/jsonEditor.scss
> +@import 'leaflet/dist/leaflet.css';
why are these imports in an unrelated scss file? Can't you just import them close to where they're used (https://github.com/open-formulieren/formio-builder/blob/main/src/registry/map/index.ts)? And preferably a `preview.scss` file that loads these libraries, so we have a consistent pattern of loading stylesheets for a given context: https://github.com/open-formulieren/formio-builder/blob/2d64b61d74ef79145a401dbe22debec0adef36cc/src/registry/email/preview.tsx#L7

2025-01-08 11:38 UTC, sergei-maertens commented on src/registry/map/preview.tsx
> +            }}
what do these control? Does it mean once I've drawn something, I can't remove it anymore from the map?

2025-01-08 11:38 UTC, sergei-maertens commented on tsconfig.json
> +    "skipLibCheck": true,
what's the impact of this? I don't like this part from the documentation:

> ...at the expense of type-system accuracy

2025-01-08 16:12 UTC, robinmolen commented on src/registry/map/preview.tsx
> +            }}
Yeah they add delete and edit buttons to the map. They are a bit cumbersome when using, so i opted to remove them..
At the moment only 1 shape is allowed. So when you create a new one, the old shape is removed. This does mean that once you have added a shape, you cannot clear it..

Im taking a look if we can change the behavior of these buttons (i.e. remove all shapes when you click the button, instead of having to click to shape and then save the deletion). For reference, this is how it normally looks https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

2025-01-08 17:11 UTC, sergei-maertens commented on src/registry/map/preview.tsx
> +            }}
Yeah not being able to make corrections is a problem. I think it's probably best to enable the delete, but leave the edit disabled and I'm sure there will be accessibility feedback about this in the future.

2025-01-09 11:10 UTC, robinmolen commented on tsconfig.json
> +    "skipLibCheck": true,
This skips type checking of *.d.ts files. With this, only the *.d.ts files that we directly use are type checked.

This is a 'solution' for a typescript error originating from `node_modules/react-leaflet-draw/src/index.d.ts`.

As we discussed in the office, maybe better to isolate this, or to solve this another way. I've gone trough the repo/issues of react-leaflet-draw, but i haven't found anything related to this.. So i created a ticket, asking their advice about using typescript https://github.com/alex3165/react-leaflet-draw/issues/188

2025-01-14 10:40 UTC, robinmolen commented on tsconfig.json
> +    "skipLibCheck": true,
I've created a PR for this issue: https://github.com/alex3165/react-leaflet-draw/pull/189. Hopefully this gets resolved soon, so that we can remove the `"skipLibCheck": true`.

I have added a issue to the backlog to clean this up https://github.com/open-formulieren/open-forms/issues/5017

2025-01-14 10:52 UTC, robinmolen commented on i18n/messages/nl.json
> +    "defaultMessage": "Lijn interacties",
Yeah 'shapes' is probably better/easier to describe this that 'interactions'..

2025-01-14 11:42 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Gebruikers kunnen een punt aanduiden op de kaart",
```suggestion
    "defaultMessage": "Gebruikers kunnen een punt aanduiden op de kaart.",
```
ironic that the "punt" sentence is missing a "punt" :laughing:

2025-01-14 11:42 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Kaartmateriaal instellingen",
```suggestion
    "defaultMessage": "Kaartinstellingen",
```

2025-01-14 11:42 UTC, sergei-maertens commented on i18n/messages/nl.json
> +    "defaultMessage": "Mogelijke kaartmateriaalvormen",
```suggestion
    "defaultMessage": "Beschikbare vormen",
```
maybe?

2025-01-14 11:42 UTC, sergei-maertens commented on src/registry/map/edit.tsx
> +  },
This will require a data migration and import patcher in the backend - do we have that?

2025-01-14 11:42 UTC, sergei-maertens commented on src/registry/map/interaction-configuration.tsx
> +        description="Interaction configuration panel title"
```suggestion
        description="Map interaction configuration panel title"
```
keep in mind that messages are global so you need to provide sufficient context in the description for translators :)

2025-01-14 11:42 UTC, sergei-maertens commented on src/registry/map/map-configuration.tsx
> +        defaultMessage="Initial focus"
Probably best to also update the description to make it a bit more accurate. Translation files need to be updated anyway.

2025-01-14 11:42 UTC, sergei-maertens commented on tsconfig.json
> +    "skipLibCheck": true,
let's include the patch-package patch in this PR as well, following our Slack discussion.

2025-01-14 13:38 UTC, robinmolen commented on src/registry/map/interaction-configuration.tsx
> +        description="Interaction configuration panel title"
Ah yeah, check

2025-01-14 13:39 UTC, robinmolen commented on tsconfig.json
> +    "skipLibCheck": true,
Yes, i've added it 🙂

2025-01-14 13:44 UTC, robinmolen commented on i18n/messages/nl.json
> +    "defaultMessage": "Mogelijke kaartmateriaalvormen",
Yeah, sounds good

2025-01-14 13:45 UTC, robinmolen commented on src/registry/map/map-configuration.tsx
> +        defaultMessage="Initial focus"
Check, yeah probably best.. Will do

2025-01-14 14:01 UTC, robinmolen commented on src/registry/map/edit.tsx
> +  },
The import is a good one, that is indeed needed..

2025-01-14 15:42 UTC, robinmolen commented on src/registry/map/edit.tsx
> +  },
Like we discussed via slack, i've added migration converters and a database migration script. The migration converters get used by the import, ensuring map components have the interactions configuration

2025-01-15 10:11 UTC, merged